### ISSUE TITLE
4.2.1 Release checklist

### ISSUE THREAD

**Issue by Tratcher** [aspnet/AspNetKatana#452]
- [x] Ensure there's a release branch created
- [x] Ensure the `Version.props` has the `PreReleaseVersionLabel` updated to the next version
- [x] Identify and validate the build on the CI pipeline
- [x] Release the build
- [x] Tag the commit
- [x] Publish release notes
- [x] Close the old milestone
- [x] Announce on social media
- [ ] Set the preview branch to protected
- [ ] Delete the previous preview branch
- [x] Request source code archival
