### ISSUE TITLE
4.2.2 release checklist

### ISSUE THREAD

**Issue by Tratcher** [aspnet/AspNetKatana#465]
- [x] Ensure the `Version.props` has the `PreReleaseVersionLabel` updated to the next preview - https://github.com/aspnet/AspNetKatana/pull/466
- [x] Identify and validate the build on the `microsoft-reverse-proxy-official` pipeline - https://dev.azure.com/dnceng/internal/_build/results?buildId=1763624&view=results
- [x] Release the build
- [x] Tag the commit
- [x] Draft release notes
- [x] Publish release notes
- [x] Close the old milestone
- [ ] ~~Announce on social media~~
- [x] Request source code archival
